/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mn.ui;

import mn.ui.commons.listeners.MainSetter;
import mn.ui.panels.CalendrierPanel;
import mn.ui.panels.OperationUI.CommandePanel;
import mn.ui.panels.FournisseurPanel;
import mn.ui.panels.LivreurPanel;
import mn.ui.panels.OperationPerLivreur;
import mn.ui.panels.RenduPanel;

/**
 *
 * @author Lars Ratovo
 */
public class Main extends javax.swing.JPanel {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.bclient.addActionListener(new MainSetter(this.main,new FournisseurPanel()));
        this.blivreur.addActionListener(new MainSetter(this.main,new LivreurPanel()));
        this.bcalendrier.addActionListener(new MainSetter(this.main,new CalendrierPanel()));
        this.bcommande.addActionListener(new MainSetter(this.main,new CommandePanel()));
        this.bcompterendulivreur.addActionListener(new MainSetter(this.main,new OperationPerLivreur()));
        this.bcompterendu.addActionListener(new MainSetter(this.main,new RenduPanel()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        bcommande = new javax.swing.JButton();
        bclient = new javax.swing.JButton();
        blivreur = new javax.swing.JButton();
        bcalendrier = new javax.swing.JButton();
        bcompterendu = new javax.swing.JButton();
        bcompterendulivreur = new javax.swing.JButton();
        main = new javax.swing.JPanel();

        jButton1.setText("jButton1");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        bcommande.setText("Commandes");
        bcommande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcommandeActionPerformed(evt);
            }
        });

        bclient.setText("Fournisseurs");
        bclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclientActionPerformed(evt);
            }
        });

        blivreur.setText("Livreurs");
        blivreur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blivreurActionPerformed(evt);
            }
        });

        bcalendrier.setText("Calendrier");
        bcalendrier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcalendrierActionPerformed(evt);
            }
        });

        bcompterendu.setText("Compte rendu");
        bcompterendu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcompterenduActionPerformed(evt);
            }
        });

        bcompterendulivreur.setText("Compte rendu par livreur");
        bcompterendulivreur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcompterendulivreurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(bcommande, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bclient, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(blivreur, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(bcalendrier, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(bcompterendu, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(bcompterendulivreur, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bclient)
                    .addComponent(blivreur)
                    .addComponent(bcommande)
                    .addComponent(bcalendrier)
                    .addComponent(bcompterendu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bcompterendulivreur)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bcommandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcommandeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bcommandeActionPerformed

    private void bclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bclientActionPerformed

    private void blivreurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blivreurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blivreurActionPerformed

    private void bcalendrierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcalendrierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bcalendrierActionPerformed

    private void bcompterenduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcompterenduActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bcompterenduActionPerformed

    private void bcompterendulivreurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcompterendulivreurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bcompterendulivreurActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcalendrier;
    private javax.swing.JButton bclient;
    private javax.swing.JButton bcommande;
    private javax.swing.JButton bcompterendu;
    private javax.swing.JButton bcompterendulivreur;
    private javax.swing.JButton blivreur;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel main;
    // End of variables declaration//GEN-END:variables
}
