/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mn.ui.commons;
import javax.swing.JTable;
import mn.Dao.Data;

/**
 *
 * @author Lars Ratovo
 */
public class Tableau<M> extends javax.swing.JPanel  {
    /**
     * Creates new form Tableau
     */
    Class type;
    Data<M> data;
    TableModel<M> tmodel;
    public Tableau() {
        initComponents();
    }
    public void init(Class type,Data<M> data,TableModel<M> tmodel) throws Exception{
        this.type=type;
        this.data=data;
        initdata(tmodel);
    }
    public void initdata(TableModel<M> tmodel) throws Exception{
        if(tmodel==null){
            this.tmodel=new TableModel<M>(data.getAll(),type,data);
        }else{
            this.tmodel=tmodel;
        }
        this.jTable1.setModel(this.getTmodel());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    public JTable getTable(){
        return jTable1;
    }

    /**
     * @return the tmodel
     */
    public TableModel<M> getTmodel() {
        return tmodel;
    }
}
